print("Hola Lyses")
print("Este es mi primer programa Python")
print("Estoy trabajando desde VS Code")
print("Aprendiendo Git desde VS Code")
print("Este cambio fue realizado directamente en GitHub")
